{
 "title": "Starlette Dashboard",
 "time": { "from": "2023-03-20T20:51:34.000Z", "to": "2023-03-20T21:06:27.000Z" },
 "panels": [
  {
   "title": "Requests over time",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(starlette_requests_total[$__rate_interval])",
     "legendFormat": "{{method}} {{path_template}}"
    }
   ]
  },
  {
   "title": "Requests Time Taken",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum by(le, path_template) (rate(starlette_requests_processing_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P99 {{path_template}}"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le, path_template) (rate(starlette_requests_processing_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P95 {{path_template}}"
    },
    {
     "expr": "histogram_quantile(0.9, sum by(le, path_template) (rate(starlette_requests_processing_time_seconds_bucket[$__rate_interval])))",
     "legendFormat": "P90 {{path_template}}"
    }
   ]
  },
  {
   "title": "Services CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Services Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "process_virtual_memory_bytes", "legendFormat": "__auto" },
    { "expr": "process_resident_memory_bytes", "legendFormat": "__auto" }
   ]
  }
 ]
}